---
- name: Stop Spark Master if Started
  command: "{{spark_home}}/sbin/stop-master.sh"

- name: Create spark-env.sh for Mesos configuration
  template: src=spark-env.sh.j2 dest="{{spark_home}}/conf/spark-env.sh"
  when: isMesosMaster is defined

- name: Launch Spark Master
  command: "{{spark_home}}/sbin/start-master.sh"

- name: Creates spark-events directory
  file: path=/tmp/spark-events state=directory owner=ubuntu

- name: Stop MesosClusterDispatch if started
  command: "{{spark_home}}/sbin/stop-mesos-dispatcher.sh --master mesos://{{ansible_eth0.ipv4.address}}:5050"
  when: isMesosMaster is defined

- name: Start MesosClusterDispatch so that we can run in Cluster mode
  command: "{{spark_home}}/sbin/start-mesos-dispatcher.sh --master mesos://{{ansible_eth0.ipv4.address}}:5050"
  when: isMesosMaster is defined


# The other way of starting slaves - via the Spark Scripts. Favour not doing this.
#- name: Add slaves to conf file
#  lineinfile: dest: "{{spark_home}}/conf/slaves" state=present line="{{hostvars[item][ansible_ssh_host]}}"
#  with_items: groups.slaves
#
#
#
#- name: Start slaves
#  command: "{{spark_home}}/sbin/start-slaves.sh"
#

